const students = [
    {
        "id": 1,
        "first_name": "Ad",
        "last_name": "Coolbear",
        "email": "acoolbear0@baidu.com"
      }, {
        "id": 2,
        "first_name": "Kirby",
        "last_name": "Ham",
        "email": "kham1@google.ca"
      }, {
        "id": 3,
        "first_name": "Marieann",
        "last_name": "Luckman",
        "email": "mluckman2@independent.co.uk"
      }, {
        "id": 4,
        "first_name": "Earvin",
        "last_name": "Gullifant",
        "email": "egullifant3@reference.com"
      }, {
        "id": 5,
        "first_name": "Bogey",
        "last_name": "Sutterby",
        "email": "bsutterby4@ask.com"
      }, {
        "id": 6,
        "first_name": "Sissie",
        "last_name": "Sans",
        "email": "ssans5@baidu.com"
      }, {
        "id": 7,
        "first_name": "Florida",
        "last_name": "Hartmann",
        "email": "fhartmann6@sbwire.com"
      }, {
        "id": 8,
        "first_name": "Linea",
        "last_name": "Kirvell",
        "email": "lkirvell7@examiner.com"
      }, {
        "id": 9,
        "first_name": "Winifield",
        "last_name": "Tripett",
        "email": "wtripett8@feedburner.com"
      }, {
        "id": 10,
        "first_name": "Taber",
        "last_name": "Girodon",
        "email": "tgirodon9@si.edu"
      }, {
        "id": 11,
        "first_name": "Bab",
        "last_name": "Marquiss",
        "email": "bmarquissa@bloglines.com"
      }, {
        "id": 12,
        "first_name": "Elladine",
        "last_name": "Dowzell",
        "email": "edowzellb@guardian.co.uk"
      }, {
        "id": 13,
        "first_name": "Ezri",
        "last_name": "Chambers",
        "email": "echambersc@ed.gov"
      }, {
        "id": 14,
        "first_name": "Horst",
        "last_name": "Rowlands",
        "email": "hrowlandsd@infoseek.co.jp"
      }, {
        "id": 15,
        "first_name": "Licha",
        "last_name": "Roscamp",
        "email": "lroscampe@japanpost.jp"
      }, {
        "id": 16,
        "first_name": "Clementius",
        "last_name": "Armer",
        "email": "carmerf@ebay.co.uk"
      }, {
        "id": 17,
        "first_name": "Tanner",
        "last_name": "Challender",
        "email": "tchallenderg@answers.com"
      }, {
        "id": 18,
        "first_name": "Glen",
        "last_name": "Slegg",
        "email": "gsleggh@miitbeian.gov.cn"
      }, {
        "id": 19,
        "first_name": "Ingrim",
        "last_name": "McCawley",
        "email": "imccawleyi@blog.com"
      }, {
        "id": 20,
        "first_name": "Kaylyn",
        "last_name": "Sabates",
        "email": "ksabatesj@ftc.gov"
      }
      
]

module.exports = students